language: go
sudo: false
go:
  - 1.12
branches:
  only:
  - master
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci -package github.com/dapperlabs/dappauth -v
